[workspace]
members = [
    "omokoda-core",
    "omokoda-hermetic",
    "omokoda-mesh",
    "omokoda-cli",
    "omokoda-acp",
    "zangbeto-stub",
    "nautilus_integration",
    "nist_entropy",
    "oso-parser",
    "oso-compiler",
    "oso-sdk",
]
resolver = "2"

[profile.dev]
debug = 0
strip = "debuginfo"
split-debuginfo = "off"
incremental = false
