#!/usr/bin/env python3
"""
transform_repo.py — SkillForge Transformation stage.

Given the Analysis output for a human-first repo, generate an *agent-native
gateway* that sits in front of the project and exposes the surfaces agents need
but the repo lacks: MCP tool discovery + invocation, a REST proxy for every
detected route, an OpenAPI spec, an agent profile (goals / memory namespace),
and a Dockerfile so the whole thing runs sandboxed.

The gateway is a sidecar — it never edits the upstream project's own code, so
the transformation is safe and reversible. It proxies to UPSTREAM_URL at run
time. This makes *any* repo agent-callable without touching its internals.

Usage:
    transform_repo.py --name <skill> --analysis <analysis.json|-> --out <dir>
Emits one JSON object on stdout describing the generated wrapper.
"""
import argparse
import json
import os
import sys
import textwrap

# The generic gateway. Identical across every forge; behavior comes from the
# generated routes.json it reads at startup. Written verbatim into the wrapper.
MCP_SERVER = r'''#!/usr/bin/env python3
"""Agent-native gateway generated by SkillForge. Reads routes.json and exposes:
  GET  /health          liveness
  GET  /mcp             MCP-style tool discovery (one tool per route)
  POST /mcp/invoke      {"tool": name, "path": {..}, "query": {..}, "body": {..}}
  GET  /openapi.json    machine-readable spec
  *                     transparent REST proxy to UPSTREAM_URL
"""
import json
import os
import pathlib

import httpx
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

CFG = json.loads((pathlib.Path(__file__).parent / "routes.json").read_text())
UPSTREAM = os.environ.get("UPSTREAM_URL", CFG.get("upstream_default", "")).rstrip("/")
app = FastAPI(title=CFG["name"] + " (agent-native gateway)")


def _split(route_str):
    method, _, path = route_str.partition(" ")
    return method.upper(), path


@app.get("/health")
async def health():
    return {"status": "ok", "skill": CFG["name"], "upstream_configured": bool(UPSTREAM)}


@app.get("/mcp")
async def mcp_discovery():
    tools = []
    for name, route in CFG["routes"].items():
        method, path = _split(route)
        params = [seg[1:-1] for seg in path.split("/") if seg.startswith("{")]
        tools.append({
            "name": name,
            "method": method,
            "path": path,
            "path_params": params,
            "description": f"{method} {path}",
        })
    return {"skill": CFG["name"], "protocol": "mcp/1", "tools": tools}


@app.post("/mcp/invoke")
async def mcp_invoke(request: Request):
    body = await request.json()
    tool = body.get("tool")
    route = CFG["routes"].get(tool)
    if not route:
        return JSONResponse({"error": f"unknown tool '{tool}'"}, status_code=404)
    if not UPSTREAM:
        return JSONResponse({"error": "UPSTREAM_URL not configured"}, status_code=503)
    method, path = _split(route)
    for k, v in (body.get("path") or {}).items():
        path = path.replace("{" + k + "}", str(v))
    url = UPSTREAM + path
    async with httpx.AsyncClient(timeout=30) as client:
        r = await client.request(method, url, params=body.get("query"),
                                 json=body.get("body"))
    ct = r.headers.get("content-type", "")
    payload = r.json() if ct.startswith("application/json") else r.text
    return JSONResponse({"status": r.status_code, "data": payload})


@app.get("/openapi.json")
async def openapi_spec():
    return json.loads((pathlib.Path(__file__).parent / "openapi.json").read_text())
'''

DOCKERFILE = '''FROM python:3.11-slim
WORKDIR /gateway
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE {port}
ENV UPSTREAM_URL=""
CMD ["uvicorn", "mcp_server:app", "--host", "0.0.0.0", "--port", "{port}"]
'''

REQUIREMENTS = "fastapi==0.115.0\nuvicorn==0.30.6\nhttpx==0.27.2\n"


def build_openapi(name, routes):
    paths = {}
    for _, route in routes.items():
        method, _, path = route.partition(" ")
        paths.setdefault(path, {})[method.lower()] = {
            "summary": f"{method} {path}",
            "responses": {"200": {"description": "OK"}},
        }
    return {
        "openapi": "3.0.3",
        "info": {"title": f"{name} agent-native gateway", "version": "1.0.0"},
        "paths": paths,
    }


def build_agent_profile(name, analysis):
    return {
        "agent_profile": {
            "name": name,
            "kind": "service-skill",
            "goals": [f"expose {name} as an agent-callable, chainable skill"],
            "memory_namespace": f"skillforge/{name}",
            "capabilities": list(analysis.get("candidate_routes", {}).keys()),
            "language": analysis.get("language", "unknown"),
            "classification": analysis.get("classification", "Unknown"),
        },
        "mcp": {"discovery": "/mcp", "invoke": "/mcp/invoke"},
        "observability": {"receipts": True, "health": "/health"},
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--analysis", required=True, help="path or '-' for stdin")
    ap.add_argument("--out", required=True)
    ap.add_argument("--port", type=int, default=8900)
    args = ap.parse_args()

    try:
        raw = sys.stdin.read() if args.analysis == "-" else open(args.analysis).read()
        analysis = json.loads(raw)
    except Exception as e:
        print(json.dumps({"ok": False, "error": f"bad analysis: {e}"}))
        return

    name = args.name
    routes = dict(analysis.get("candidate_routes") or {})
    if not routes:
        routes = {"root": "GET /"}

    out = os.path.abspath(args.out)
    os.makedirs(out, exist_ok=True)

    files = {}
    routes_cfg = {
        "name": name,
        "upstream_default": analysis.get("base_url_hint") or "",
        "routes": routes,
    }
    files["routes.json"] = json.dumps(routes_cfg, indent=2)
    files["mcp_server.py"] = MCP_SERVER
    files["requirements.txt"] = REQUIREMENTS
    files["Dockerfile"] = DOCKERFILE.format(port=args.port)
    files["openapi.json"] = json.dumps(build_openapi(name, routes), indent=2)
    files["agent.json"] = json.dumps(build_agent_profile(name, analysis), indent=2)
    files["README.md"] = textwrap.dedent(f"""\
        # {name} — agent-native gateway (generated by SkillForge)

        This sidecar makes `{name}` callable by agents without modifying the
        upstream project. Point `UPSTREAM_URL` at the running service.

        - MCP discovery: `GET /mcp`
        - MCP invoke:    `POST /mcp/invoke` `{{"tool":"...","path":{{}},"query":{{}},"body":{{}}}}`
        - OpenAPI:       `GET /openapi.json`
        - Health:        `GET /health`

        Run locally:
            pip install -r requirements.txt
            UPSTREAM_URL=http://localhost:PORT uvicorn mcp_server:app --port {args.port}

        Run sandboxed:
            docker build -t skillforge-{name} .
            docker run -e UPSTREAM_URL=... -p {args.port}:{args.port} skillforge-{name}
        """)

    for fname, content in files.items():
        with open(os.path.join(out, fname), "w", encoding="utf-8") as f:
            f.write(content)

    added_surfaces = ["mcp_server", "openapi_spec", "rest_proxy",
                      "agent_profile", "dockerfile"]
    print(json.dumps({
        "ok": True,
        "name": name,
        "output_dir": out,
        "port": args.port,
        "wrapper_base_url": f"http://localhost:{args.port}",
        "generated_files": sorted(files.keys()),
        "added_surfaces": added_surfaces,
        "gateway_routes": {
            "health": "GET /health",
            "mcp_discover": "GET /mcp",
            "mcp_invoke": "POST /mcp/invoke",
            "openapi": "GET /openapi.json",
        },
    }))


if __name__ == "__main__":
    main()
