// Generated by oso-move v0.1.0 — DO NOT EDIT
// Contract: JobContract (work)
// OSO-IR version: 1.0
// Minimum tier: 1  Currency: ASE

module oso_contracts::job_contract {

    use sui::tx_context::TxContext;
    use sui::tx_context;
    use sui::transfer;
    use sui::event;
    use sui::object::{Self, UID};

    /// Auto-generated from AssetSpec "Job"
    struct Job has key, store {
        id: UID,
        job_id: u64, // TODO: resolve field type
        creator: u64, // TODO: resolve field type
        assignee: u64, // TODO: resolve field type
        budget_mist: u64, // TODO: resolve field type
        deadline_unix: u64, // TODO: resolve field type
        description_blob_id: u64, // TODO: resolve field type
        result_blob_id: u64, // TODO: resolve field type
        state: u64, // TODO: resolve field type
    }

    /// Auto-generated from AssetSpec "JobResult"
    struct JobResult has key, store {
        id: UID,
        job_id: u64, // TODO: resolve field type
        provider: u64, // TODO: resolve field type
        output_hash: u64, // TODO: resolve field type
        quality_score: u64, // TODO: resolve field type
        completed_at: u64, // TODO: resolve field type
        evidence_hash: u64, // TODO: resolve field type
    }

    // --- Lifecycle state constants ---
    const STATE_CREATED: u8 = 0;
    const STATE_ASSIGNED: u8 = 1;
    const STATE_ACCEPTED: u8 = 2;
    const STATE_STARTED: u8 = 3;
    const STATE_EXECUTED: u8 = 4;
    const STATE_VERIFIED: u8 = 5;
    const STATE_SETTLED: u8 = 6;

    /// Lifecycle transition: CREATED → ASSIGNED
    public entry fun transition_created_to_assigned(ctx: &mut TxContext) {
        // TODO: assert capability grants
        // assert!(has_capability(tx_context::sender(ctx), b"GPU_COMPUTE"), ECAPABILITY_MISSING);
        // state transition: CREATED → ASSIGNED
        let _sender = tx_context::sender(ctx);
        // TODO: update state field to STATE_ASSIGNED
    }

    /// Lifecycle transition: ASSIGNED → ACCEPTED
    public entry fun transition_assigned_to_accepted(ctx: &mut TxContext) {
        // TODO: assert capability grants
        // assert!(has_capability(tx_context::sender(ctx), b"GPU_COMPUTE"), ECAPABILITY_MISSING);
        // state transition: ASSIGNED → ACCEPTED
        let _sender = tx_context::sender(ctx);
        // TODO: update state field to STATE_ACCEPTED
    }

    /// Lifecycle transition: ACCEPTED → STARTED
    public entry fun transition_accepted_to_started(ctx: &mut TxContext) {
        // TODO: assert capability grants
        // assert!(has_capability(tx_context::sender(ctx), b"GPU_COMPUTE"), ECAPABILITY_MISSING);
        // state transition: ACCEPTED → STARTED
        let _sender = tx_context::sender(ctx);
        // TODO: update state field to STATE_STARTED
    }

    /// Lifecycle transition: STARTED → EXECUTED
    public entry fun transition_started_to_executed(ctx: &mut TxContext) {
        // TODO: assert capability grants
        // assert!(has_capability(tx_context::sender(ctx), b"GPU_COMPUTE"), ECAPABILITY_MISSING);
        // state transition: STARTED → EXECUTED
        let _sender = tx_context::sender(ctx);
        // TODO: update state field to STATE_EXECUTED
    }

    /// Lifecycle transition: EXECUTED → VERIFIED
    public entry fun transition_executed_to_verified(ctx: &mut TxContext) {
        // TODO: assert capability grants
        // assert!(has_capability(tx_context::sender(ctx), b"GPU_COMPUTE"), ECAPABILITY_MISSING);
        // assert_evidence: type=WorkCompletion
        // TODO: EvidenceCommitment check before settlement
        // state transition: EXECUTED → VERIFIED
        let _sender = tx_context::sender(ctx);
        // TODO: update state field to STATE_VERIFIED
    }

    /// Lifecycle transition: VERIFIED → SETTLED
    public entry fun transition_verified_to_settled(ctx: &mut TxContext) {
        // TODO: assert capability grants
        // assert!(has_capability(tx_context::sender(ctx), b"GPU_COMPUTE"), ECAPABILITY_MISSING);
        // assert_evidence: type=WorkCompletion
        // TODO: EvidenceCommitment check before settlement
        // state transition: VERIFIED → SETTLED
        let _sender = tx_context::sender(ctx);
        // TODO: update state field to STATE_SETTLED
    }

    /// Settlement: distribute Àṣẹ per fee routing policy.
    /// currency=ASE fee_routing=6-pool provider_share=0.85
    public entry fun settle(provider: address, amount: u64, ctx: &mut TxContext) {
        // TRANSFER opcode → sui::transfer::public_transfer stub
        // TODO: sui::transfer::public_transfer(coin, provider);
        // EMIT_RECEIPT opcode → event emission stub
        // TODO: event::emit(SettlementReceipt { provider, amount });
        // Èṣù tithe: 0.0369 of settlement flows to justice pool
        // TODO: transfer tithe to ESU_JUSTICE_POOL address
        let _ctx = ctx;
        let (_provider, _amount) = (provider, amount);
    }

    /// AGENT_CALL opcode — cross-module call stub.
    public entry fun agent_call(target: address, _ctx: &mut TxContext) {
        // TODO: call target module via dynamic dispatch (Sui PTB)
        let _target = target;
    }

}
